//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class appaccount
    {
        public int appid { get; set; }
        public string appname { get; set; }
        public string adminuserid { get; set; }
        public short STATUS { get; set; }
    }
}
