//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class calcconfig
    {
        public long configid { get; set; }
        public long appid { get; set; }
        public long buildid { get; set; }
        public long roomid { get; set; }
        public long classid { get; set; }
        public decimal price { get; set; }
        public string customprice { get; set; }
        public Nullable<long> createuserid { get; set; }
        public System.DateTime createtime { get; set; }
        public short STATUS { get; set; }
    }
}
