//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class financelog
    {
        public long financeid { get; set; }
        public Nullable<long> appid { get; set; }
        public Nullable<long> buildid { get; set; }
        public Nullable<long> roomid { get; set; }
        public Nullable<long> customerid { get; set; }
        public Nullable<short> type { get; set; }
        public long calclogid { get; set; }
        public Nullable<long> businessid { get; set; }
        public Nullable<decimal> money { get; set; }
        public string fromaccount { get; set; }
        public string toaccount { get; set; }
        public Nullable<int> create_operator_id { get; set; }
        public string create_operator_name { get; set; }
        public System.DateTime create_time { get; set; }
        public Nullable<int> check_operator_id { get; set; }
        public string check_operator_name { get; set; }
        public Nullable<System.DateTime> check_time { get; set; }
        public short STATUS { get; set; }
    }
}
