//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class financeclass
    {
        public long classid { get; set; }
        public long appid { get; set; }
        public string classname { get; set; }
        public short calctype { get; set; }
        public string unit { get; set; }
        public decimal price { get; set; }
        public string customprice { get; set; }
        public bool isenable { get; set; }
        public short STATUS { get; set; }
    }
}
