//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<building> building { get; set; }
        public DbSet<calcconfig> calcconfig { get; set; }
        public DbSet<calcvaluelog> calcvaluelog { get; set; }
        public DbSet<customer> customer { get; set; }
        public DbSet<financeclass> financeclass { get; set; }
        public DbSet<financelog> financelog { get; set; }
        public DbSet<rent> rent { get; set; }
        public DbSet<rentmonth> rentmonth { get; set; }
        public DbSet<role> role { get; set; }
        public DbSet<rooms> rooms { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<session> session { get; set; }
        public DbSet<appaccount> appaccount { get; set; }
    }
}
