//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class rentmonth
    {
        public long rentmonthid { get; set; }
        public long appid { get; set; }
        public long buildid { get; set; }
        public long roomid { get; set; }
        public Nullable<long> customerid { get; set; }
        public short year { get; set; }
        public short month { get; set; }
        public decimal payment_money { get; set; }
        public bool payment_status { get; set; }
        public string payment_type { get; set; }
        public long calc_operator_id { get; set; }
        public string calc_operator_name { get; set; }
        public Nullable<System.DateTime> calc_time { get; set; }
        public long rent_operator_id { get; set; }
        public string rent_operator_name { get; set; }
        public Nullable<System.DateTime> rent_time { get; set; }
        public short STATUS { get; set; }
    }
}
