//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public string rolename { get; set; }
        public string defaultright { get; set; }
        public string allright { get; set; }
        public string rolecol { get; set; }
        public string description { get; set; }
        public Nullable<short> STATUS { get; set; }
    }
}
