//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public long userid { get; set; }
        public long appid { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string realname { get; set; }
        public string credentials_type { get; set; }
        public string credentials_code { get; set; }
        public string credentials_pic { get; set; }
        public string mobile { get; set; }
        public string wechat { get; set; }
        public string qq { get; set; }
        public string role { get; set; }
        public string roleright { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public short STATUS { get; set; }
    }
}
